<?php

$title = 'Edit invoice';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'mvitinvoice',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('number'));
echo $this->formRow($form->get('base_date'));
echo $this->formRow($form->get('vat'));
echo $this->formRow($form->get('due_days'));
echo $this->formRow($form->get('sent_date'));
echo $this->formRow($form->get('payed_date'));
echo $this->formRow($form->get('client_id'));
echo $this->formRow($form->get('client_name'));
echo $this->formRow($form->get('reference'));
echo $this->formRow($form->get('text'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
