<?php
$title = 'Invoices';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('mvitinvoice', array(
        'action'=>'add'));?>">Create new invoice</a></p>

<table class="table">
<tr>
    <th>number</th>
    <th>base_date</th>
    <th>sent_date</th>
    <th>payed_date</th>
    <th>due_days</th>
    <th>client</th>
    <th>reference</th>
    <th>text</th>
    <th>&nbsp;</th>
</tr>

<?php foreach($invoices as $invoice) : ?>
<tr>
    <td><?php echo $this->escapeHtml($invoice->number);?></td>
    <td><?php echo $this->escapeHtml($invoice->base_date);?></td>
    <td><?php echo $this->escapeHtml($invoice->sent_date);?></td>
    <td><?php echo $this->escapeHtml($invoice->payed_date);?></td>
    <td><?php echo $this->escapeHtml($invoice->due_days);?></td>
    <td><?php echo $this->escapeHtml($invoice->client_name);?></td>
    <td><?php echo $this->escapeHtml($invoice->reference);?></td>
    <td><?php echo $this->escapeHtml($invoice->text);?></td>
    <td>
        <a href="<?php echo $this->url('mvitinvoice',
            array('action'=>'edit', 'id' => $invoice->id));?>">Edit</a>
        <a href="<?php echo $this->url('mvitinvoice',
            array('action'=>'delete', 'id' => $invoice->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
